name: CD
on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    uses: ArkeonProject/organization-tools/.github/workflows/reusable-docker-build.yml@v1.1.5
    with:
      image_name: ${{ github.repository }}/backend
      mode: 'production'
      dockerfile_path: './backend/Dockerfile'
      context: './backend'
    secrets:
      PORTAINER_WEBHOOK: ${{ secrets.PORTAINER_WEBHOOK_BACKEND }}

  deploy-frontend:
    uses: ArkeonProject/organization-tools/.github/workflows/reusable-docker-build.yml@v1.1.5
    with:
      image_name: ${{ github.repository }}/frontend
      mode: 'production'
      dockerfile_path: './frontend/Dockerfile'
      context: './frontend'
    secrets:
      PORTAINER_WEBHOOK: ${{ secrets.PORTAINER_WEBHOOK_FRONTEND }}
