name: CI
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop, main]

jobs:
  ci:
    name: Continuous Integration
    uses: ArkeonProject/organization-tools/.github/workflows/ci-python.yml@v1.1.5
    with:
      python-version: '3.12'
      working-directory: 'backend'
      run-lint: true
      run-format-check: false
      run-tests: true
    secrets: inherit
